// Mutation pass over the test suite: break the game on purpose, one way at a time, and check
// that the suite notices. A green suite is evidence only for the breaks it is known to catch.
//
//   node tools/mutate.mjs        every mutant, one after another; exits 1 if any survives
//
// It works on a copy in the OS temp directory and never touches the working tree. The suite's
// own temporary directories go inside that copy, and the unmutated suite must leave none behind.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// [what breaks, file, exact text, replacement]. Each text must occur exactly once.
const MUTANTS = [
  ['animation drops the care reaction', 'hosting/scene.mjs', "const reaction = reply.split('\\n').find(line => line.startsWith('quirk:'));", 'const reaction = null;'],
  ['animation misses an unseen remote move', 'hosting/page.mjs', 'lastSceneAt!==null&&scene.recent', 'false&&scene.recent'],
  ['animation repeats an already predicted journey', 'hosting/page.mjs', '&&scene.recent.at!==knownMoveAt', ''],
  ['sliding skips intermediate columns', 'hosting/scene.mjs', 'STEP_MS = 500', 'STEP_MS = 1'],
  ['sliding loses upcoming movements', 'hosting/scene.mjs', 'HORIZON_MS = 16000', 'HORIZON_MS = 0'],
  ['a shuffle loses its vertical step', 'hosting/scene.mjs', 'dx: place.dx + dx, dy, furrow: false', 'dx: place.dx + dx, dy: 0, furrow: false'],
  ['a shuffle never settles back', 'hosting/scene.mjs', 'now >= at + 2500', 'now >= at + 25000'],
  ['a vertical shuffle erases a mess', 'src/screen.mjs', " && !blocked.has(`${r + dy},${c}`)", ''],
  ['animation ignores reduced motion', 'hosting/page.mjs', "||matchMedia('(prefers-reduced-motion: reduce)').matches", ''],
  ['animation leaves old frames after a command', 'hosting/page.mjs', 'revision++; stopFrames();', 'revision++;'],
  ['animation ignores scheduled frames', 'hosting/page.mjs', 'for(const frame of frames){', 'for(const frame of []){'],
  ['browser negotiation hides ASCII from text agents', 'hosting/http.mjs', "request.headers.get('sec-fetch-dest') === 'document' && ", ''],
  ['refresh submits instead of reading', 'hosting/page.mjs', "fetch(view,{method:'GET'", "fetch(view,{method:'POST'"],
  ['refresh takes keyboard focus', 'hosting/page.mjs', 'refreshing=true; const before=revision;', 'refreshing=true; input.blur(); const before=revision;'],
  ['refresh accepts a stale response', 'hosting/page.mjs', '||before!==revision', ''],
  ['refresh polls hidden tabs', 'hosting/page.mjs', 'if(document.hidden||busy||refreshing)return;', 'if(busy||refreshing)return;'],
  ['refresh overlaps background reads', 'hosting/page.mjs', 'if(document.hidden||busy||refreshing)return;', 'if(document.hidden||busy)return;'],
  ['refresh discards the history view', 'hosting/page.mjs', 'fetch(view,{', "fetch('/',{"],
  ['refresh displays a failed response', 'hosting/page.mjs', '!response.ok||before!==revision', 'before!==revision'],
  ['refresh repeats POST documents', 'hosting/http.mjs', "route === '/' && ['GET', 'HEAD'].includes(request.method)", 'true'],
  ['refresh omits the text page header', 'hosting/http.mjs', "{ refresh: status >= 400 ? '60' : '15' }", '{}'],
  ['keyboard feeds on the wrong key', 'hosting/page.mjs', "f:'feed',c:'clean',p:'pet'", "f:'clean',c:'feed',p:'pet'"],
  ['keyboard held keys automate care', 'hosting/page.mjs', 'event.repeat||', ''],
  ['keyboard typing a command triggers care', 'hosting/page.mjs', '||document.activeElement===input', ''],
  ['keyboard hotkeys act on a grave', 'hosting/page.mjs', "verb&&phase==='alive'", 'verb'],
  ['a checkpoint forgets accumulated care', 'src/checkpoint.mjs', 'care: careTotals(prefix)', 'care: { feed: 0, clean: 0, pet: 0 }'],
  ['a checkpoint forgets its latest feed', 'src/checkpoint.mjs', 'motion: movement, biography, fed,', 'motion: movement, biography, fed: null,'],
  ['a checkpoint forgets its biography', 'src/checkpoint.mjs', 'if (log.checkpoint) biography = { ...log.checkpoint.biography };', ''],
  ['a checkpoint discards same-millisecond care', 'src/checkpoint.mjs', 'visits: log.visits.filter(v => v.t >= latest)', 'visits: log.visits.filter(v => v.t > latest)'],
  ['hosted visits overwrite competing care', 'hosting/store.mjs', 'WHERE id = 1 AND revision = ?', 'WHERE id = 1 AND revision >= ?'],
  ['a losing transaction appends a care event', 'hosting/store.mjs', 'SELECT ?, ?, ?, ? FROM rock WHERE id = 1 AND token = ?', 'SELECT ?, ?, ?, ? FROM rock WHERE id = 1 AND token != ?'],
  ['the hosted birth leaves no permanent name', 'hosting/store.mjs', 'if (!head) statements.push(', 'if (false) statements.push('],
  ['a missing hosted rock becomes a title', 'hosting/store.mjs', "if (begun || event) throw new Error('missing rock with an existing birth ledger');", ''],
  ['the hosted clock goes backwards', 'hosting/store.mjs', 'Math.max(now, head?.observed_at ?? now)', 'now'],
  ['the hosted grave is not persisted', 'hosting/store.mjs', 'log = { ...log, died: result.died };', ''],
  ['hosted credit has no duration bound', 'hosting/store.mjs', 'if (outage.end - outage.start > MAX_OUTAGE_MS)', 'if (false)'],
  ['hosted credit can be silently replaced', 'hosting/store.mjs', 'recorded.start !== outage.start || recorded.end !== outage.end', 'false'],
  ['maintenance allows new care', 'hosting/http.mjs', "if (env.ROCK_MAINTENANCE === '1')", 'if (false)'],
  ['oversized hosted bodies are accepted', 'hosting/http.mjs', 'if (length > 1024)', 'if (false)'],
  ['hosted API has no rate limit', 'hosting/store.mjs', 'return row.count > 600;', 'return false;'],
  ['hosted screens may be cached', 'hosting/http.mjs', "'cache-control': 'no-store'", "'cache-control': 'public'"],
  ['a pet is +1', 'src/rules.mjs', 'pet: 2,', 'pet: 1,'],
  ['a mess lowers the ceiling by 2', 'src/rules.mjs', 'messCeil: 3,', 'messCeil: 2,'],
  ['death after 47h', 'src/rules.mjs', 'graceH: 48,', 'graceH: 47,'],
  ['messes fall due at 01:00 and 13:00', 'src/engine.mjs', '(Math.floor(t / MESS_MS) + 1) * MESS_MS;', '(Math.floor(t / MESS_MS) + 1) * MESS_MS + HOUR;'],
  ['the first mess does not lower the ceiling', 'src/engine.mjs', '10 - R.messCeil * messes)', '10 - R.messCeil * Math.max(0, messes - 1))'],
  ['growing hunger pain counted twice', 'src/engine.mjs', 'pain = e0 * u + (r * u * u) / 2;', 'pain = e0 * u + r * u * u;'],
  ['no hunger pain at hunger 10', 'src/engine.mjs', 'if (tau > tFull) pain += PAIN_MAX * (tau - tFull);', ''],
  ['the floor time ignores growing pain', 'src/engine.mjs', 'return tPain + (2 * rest) / (b + Math.sqrt(b * b + 4 * a * rest));', 'return tPain + rest / b;'],
  ['the drain reads the hunger at the END of a stretch', 'src/engine.mjs', 's.happy = Math.max(-10, s.happy - drain(s.hunger, s.messes, dt));', 's.happy = Math.max(-10, s.happy - drain(Math.min(10, s.hunger + R.hungerPerHour * dt), s.messes, dt));'],
  ['any visit resets the sorrow clock', 'src/engine.mjs', 'if (s.happy > -10) s.sorrowSince = null;', 's.sorrowSince = null;'],
  ['feeding never resets the starving clock', 'src/engine.mjs', 'if (s.hunger < 10) s.starvingSince = null;', ''],
  ['pets ignore the ceiling', 'src/engine.mjs', 's.happy = Math.min(ceilingOf(s.messes), s.happy + R.pet * n);', 's.happy = Math.min(10, s.happy + R.pet * n);'],
  ['clean removes one mess', 'src/engine.mjs', "else if (verb === 'clean') s.messes = 0;", "else if (verb === 'clean') s.messes = Math.max(0, s.messes - 1);"],
  ['a new mess does not pull happiness under the ceiling', 'src/engine.mjs', 's.happy = Math.min(s.happy, ceilingOf(s.messes));', ''],
  ['never filthy', 'src/engine.mjs', "cause: ceilingOf(s.messes) <= -10 ? 'filthy' : 'lonely'", "cause: 'lonely'"],
  ['a visit after death is applied', 'src/engine.mjs', '    if (s.dead) break;\n    applyVisit(s, v.acts);', '    applyVisit(s, v.acts);'],
  ['a visit exactly at the 48th hour saves it', 'src/engine.mjs', 'const end = Math.min(te, starve, sorrow);', 'const end = Math.min(te, starve, sorrow);\n  if (end === te && te < Infinity && (te === starve || te === sorrow)) { s.t = te; return; }'],
  ['trailing spaces kept', 'src/screen.mjs', "row.join('').trimEnd()", "row.join('')"],
  ['(max N) shown with no mess', 'src/screen.mjs', 'const max = s.messes > 0 ?', 'const max = s.messes >= 0 ?'],
  ['no sorrow danger line', 'src/screen.mjs', 'if (s.sorrowSince !== null) lines.push(', 'if (false) lines.push('],
  ['hunger shows 10 before it is there', 'src/screen.mjs', 'Math.min(9, Math.round(s.hunger))', 'Math.round(s.hunger)'],
  ['sad eyes from -6', 'src/screen.mjs', "if (s.happy < -5) return ';  ;';", "if (s.happy < -6) return ';  ;';"],
  ['a tie dies of sorrow', 'src/engine.mjs', "if (end === starve) s.dead = { t: end, cause: 'hungry' };", "if (end === starve && end !== sorrow) s.dead = { t: end, cause: 'hungry' };"],
  ['a starving clock due after the death survives it', 'src/engine.mjs', 'if (s.starvingSince !== null && s.starvingSince > end) s.starvingSince = null;', ''],
  ['a sorrow clock due after the death survives it', 'src/engine.mjs', 'if (s.sorrowSince !== null && s.sorrowSince > end) s.sorrowSince = null;', ''],
  ['the suggestion counts feeds from the rounded hunger', 'src/screen.mjs', 'while (Math.max(0, s.hunger - R.feed * feeds) >= 0.5) feeds++;', 'feeds = Math.ceil(Math.min(9, Math.round(s.hunger)) / R.feed);'],
  ['one pet too many when sad', 'src/screen.mjs', 'while (Math.min(10, s.happy + R.pet * pets) < 9.5) pets++;', 'while (Math.min(10, s.happy + R.pet * pets) < 9.5) pets++;\n  if (s.happy < -5) pets++;'],
  ['the first mess one column right', 'src/screen.mjs', '[7, 8], [7, 2]', '[7, 9], [7, 2]'],
  ['danger hours rounded', 'src/screen.mjs', 'const hours = ms => Math.max(0, Math.floor(ms / HOUR));', 'const hours = ms => Math.max(0, Math.round(ms / HOUR));'],
  ['days rounded', 'src/screen.mjs', 'return `${Math.floor(m / 1440)}d`;', 'return `${Math.round(m / 1440)}d`;'],
  ['hours rounded', 'src/screen.mjs', 'return `${Math.floor(m / 60)}h`;', 'return `${Math.round(m / 60)}h`;'],
  ['(max N) stops at -9', 'src/screen.mjs', '` (max ${ceilingOf(s.messes)})`', '` (max ${Math.max(-9, ceilingOf(s.messes))})`'],
  ['counts not clamped', 'src/parse.mjs', 'acts.push([w, Math.min(n, RULES.maxCount)]);', 'acts.push([w, n]);'],
  ['x0 accepted', 'src/parse.mjs', 'if (n < 1) return', 'if (false) return'],
  ['unknown words accepted', 'src/parse.mjs', 'if (!VERBS.includes(w)) return', 'if (false) return'],
  ['percent-encoding not decoded', 'src/parse.mjs', '  else text = text.replace(/%([0-9A-Fa-f]{2})/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)));', ''],
  ['log lines not trimmed (a byte-order mark breaks the log)', 'src/log.mjs', ".map(l => l.trim())", ''],
  ['the log takes any act', 'src/log.mjs', 'row.acts.every(isAct)', 'row.acts.every(Array.isArray)'],
  ['the log takes a line after the death', 'src/log.mjs', 'if (log.died) throw new Error(`${where} comes after the death`);', ''],
  ['the engine replays visits out of order', 'src/engine.mjs', "    if (!(v.t >= last)) throw new Error(`visits out of time order at ${v.t}`);\n    last = v.t;\n    if (v.t > now) break;", '    last = v.t;\n    if (v.t > now) break;'],
  ['a dead rock accepts visits', 'src/rock.mjs', 'if (s.dead) return { status: 410', 'if (false) return { status: 410'],
  ['a clock that steps back is trusted', 'src/rock.mjs', 'Math.max(now, log.born, log.checkpoint?.engine.t ?? -Infinity, log.visits.at(-1)?.t ?? -Infinity, ', 'Math.max(now, log.born, '],
  ['a recorded death does not hold the clock', 'src/rock.mjs', ', log.died?.t ?? -Infinity,', ','],
  ['a death is never recorded', 'src/rock.mjs', 'const firstSight = (log, s) => (s.dead && !log.died ? { died: s.dead } : {});', 'const firstSight = () => ({});'],
  ['a recorded death is not checked', 'src/rock.mjs', 'if (log.died && !(s.dead', 'if (false && !(s.dead'],
  ['a refused body is still logged', 'server.mjs', "(r.visit ? visitLine(r.visit) : '')", "visitLine(r.visit ?? { t: Date.now() + 1e7, acts: [['pet', 1]] })"],
  ['the append waits a moment (a race)', 'server.mjs', "if (lines) fs.appendFileSync(file, (text.endsWith('\\n') ? '' : '\\n') + lines);", "if (lines) setTimeout(() => fs.appendFileSync(file, (text.endsWith('\\n') ? '' : '\\n') + lines), Math.random() * 20);"],
  ['no newline before an append', 'server.mjs', "(text.endsWith('\\n') ? '' : '\\n') + lines", 'lines'],
  ["a missing log gives birth", "server.mjs", "    const text = fs.readFileSync(file, 'utf8');\n    const log = parseLog(text);", "    try { fs.writeFileSync(file, birthLine(now()), { flag: 'wx' }); } catch {}\n    const text = fs.readFileSync(file, 'utf8');\n    const log = parseLog(text);"],
  ['the 500 says what went wrong', 'server.mjs', 'r = { status: 500, text: BROKEN };', 'r = { status: 500, text: `error: ${e.message}. nothing was changed.` };'],
  ['no cache-control', 'server.mjs', "'cache-control': 'no-store'", "'x-cache-control': 'no-store'"],
  ["405 without Allow", "server.mjs", "return reply(() => ({ status: 405, text: `error: ${hint()}.\\n` }), { allow: 'GET, HEAD' });", "return reply(() => ({ status: 405, text: `error: ${hint()}.\\n` }));"],
  ['no body limit', 'server.mjs', 'if (size <= MAX_BODY) return void chunks.push(c);', 'return void chunks.push(c);'],
  ['the 413 waits for the end of the body', 'server.mjs', '        req.resume();', "        return void req.on('end', () => send(413, 'too big', { connection: 'close' }));"],
  ['the request path is parsed as a URL', 'server.mjs', "const route = (req.url ?? '/').split('?')[0];", "const route = new URL(req.url, 'http://localhost').pathname;"],
  ["the screen prints the Host header", "server.mjs", "either((log, t) => look(log, { now: t, host }), () => titled(200));", "either((log, t) => look(log, { now: t, host: req.headers.host }), () => titled(200));"],
  ["the title prints the Host header", 'server.mjs', "const titled = (status, error = '') => ({ status, text: error + title({ host }).text });", "const titled = (status, error = '') => ({ status, text: error + title({ host: req.headers.host }).text });"],
  ['listens on every interface', 'server.mjs', "opt('--listen') ?? '127.0.0.1'", "opt('--listen') ?? '::'"],
  // Round 2: behaviours from round 1 that no test could fail.
  ["the server gives birth at start", "server.mjs", "    if (present(file)) {\n      look(readLog(file)", "    if (!present(file)) fs.writeFileSync(file, birthLine(Date.now()), { flag: 'wx' });\n    if (present(file)) {\n      look(readLog(file)"],
  ['a clock behind the birth is trusted', 'src/rock.mjs', 'Math.max(now, log.born, ', 'Math.max(now, '],
  ['a refused act never records the death', 'src/rock.mjs', "{ status: 410, text: render(s, { now: t, host, ...seen(log, s, t) }) + `history: ${host}/history\\n`, ...firstSight(log, s) }", "{ status: 410, text: render(s, { now: t, host, ...seen(log, s, t) }) + `history: ${host}/history\\n` }"],
  ['a recorded death at the wrong moment passes', 'src/rock.mjs', 's.dead.t === log.died.t && ', ''],
  ['the 413 still acts on the part it read', 'server.mjs', "        req.removeAllListeners('end');\n", ''],
  ['the log takes a count of 1.5', 'src/log.mjs', 'Number.isInteger(a[1])', 'Number.isFinite(a[1])'],
  ['the log takes a count of 0', 'src/log.mjs', 'a[1] >= 1 &&', 'a[1] >= 0 &&'],
  ['the log takes an act of three parts', 'src/log.mjs', 'a.length === 2 &&', ''],
  ['the log takes a birth that is not a time', 'src/log.mjs', 'isTime(head?.born)', "head?.born !== undefined"],
  ['the log takes a death at no time', 'src/log.mjs', '!isTime(row.died) || ', ''],
  ['the log takes a death of any cause', 'src/log.mjs', ' || !CAUSES.includes(row.cause)', ''],
  // Round 2: the fixes.
  ['the screen prints localhost', 'server.mjs', '`127.0.0.1:${port}`', '`localhost:${port}`'],
  ['no lock', 'server.mjs', "try { return void fs.writeFileSync(lockOf(file), String(process.pid), { flag: 'wx' }); }", "try { return void fs.writeFileSync(lockOf(file), String(process.pid), { flag: 'w' }); }"],
  ['a stale lock is never taken over', 'server.mjs', 'if (pid > 0 && alive(pid)) throw', 'if (pid > 0) throw'],
  ['closing keeps the lock', 'server.mjs', "server.on('close', () => { release(); process.off('exit', release); });", "server.on('close', () => { process.off('exit', release); });"],
  ['a refused start keeps the lock', 'server.mjs', '  } catch (e) {\n    release();\n    throw e;', '  } catch (e) {\n    throw e;'],
  ["a torn log cannot be buried", "server.mjs", "catch { stem = `${kind}-unreadable-${new Date(now).toISOString()}`; }", "catch (e) { throw e; }"],
  ["a log that cannot be replayed is served", "server.mjs", "      look(readLog(file), { now: Date.now(), host }); // refuse to serve a log that cannot be replayed\n", ""],
  ['JSON bodies read as words', 'src/parse.mjs', "  try { json = /^[{\"]/.test(text) ? JSON.parse(text) : undefined; } catch { /* not JSON after all: words */ }\n", ''],
  ['the sandbox meets a bad log mid-game', 'tools/sandbox.mjs', '  look(log, { now: Date.now(), host: HOST }); // refuse a log this build cannot replay now, not mid-game\n', ''],
  ['a form key that is a verb is dropped', 'src/parse.mjs', "(VERBS.includes(String(k).toLowerCase()) ? `${k} ${v}` : String(v))", 'String(v)'],
  ['no acquisition gate', 'server.mjs', "fs.writeFileSync(gate, String(process.pid), { flag: 'wx' });", "fs.writeFileSync(gate, String(process.pid), { flag: 'w' });"],
  ['post-death visits pass persistence validation', 'src/rock.mjs', "  if (s.visits !== log.visits.length + (log.checkpoint?.engine.visits ?? 0)) throw new Error('the log contains visits at or after death');", ''],
  ['outages do not pause the engine', 'src/engine.mjs', 'export function replay(log, now) {\n  validateOutages(log);\n  const outages = log.outages ?? [];', 'export function replay(log, now) {\n  validateOutages(log);\n  const outages = [];'],
  ['the replayer forgets downtime', 'src/engine.mjs', 'export function replayer(log) {\n  validateOutages(log);\n  const outages = log.outages ?? [];', 'export function replayer(log) {\n  validateOutages(log);\n  const outages = [];'],
  ['the replayer splits the flow at every moment', 'src/engine.mjs', '    const then = { ...s };\n    if (!then.dead) advance(then, t, outages);\n    return then;', '    if (!s.dead) advance(s, t, outages);\n    return { ...s };'],
  ['the replayer goes back in time', 'src/engine.mjs', '    if (!(t >= prev)) throw new Error(`moments out of time order at ${t}`);\n', ''],
  ['starvation advances during downtime', 'src/engine.mjs', 'if (s.starvingSince !== null) s.starvingSince += paused;', ''],
  ['sorrow advances during downtime', 'src/engine.mjs', 'if (s.sorrowSince !== null) s.sorrowSince += paused;', ''],
  ['a mess appears as the outage starts', 'src/engine.mjs', 'advanceActive(s, o.start, false)', 'advanceActive(s, o.start, true)'],
  ['recovery skips its due mess', 'src/engine.mjs', 'end === o.end && end % MESS_MS === 0', 'false && end % MESS_MS === 0'],
  ['adjoining outages create a mess between them', 'src/engine.mjs', ' && outages[i + 1]?.start !== end', ''],
  ['a recorded death can receive credit', 'src/rock.mjs', "  if (log.died) throw new Error('a recorded death is permanent');", ''],
  ['future downtime can be credited', 'src/rock.mjs', ' || outage.end > now', ''],
  ['credit without evidence', 'src/outages.mjs', "typeof o.evidence !== 'string' || !EVIDENCE.test(o.evidence)", 'false'],
  ['care inside an outage is accepted', 'src/outages.mjs', 'log.visits.some(v => v.t >= o.start && v.t < o.end)', 'false'],
  ['personality changes on every reply', 'src/story.mjs', "profile.dominant?.id ?? 'balanced'", "((globalThis.__mutantQuirk = (globalThis.__mutantQuirk ?? 0) + 1) % 2 ? 'feed' : 'pet')"],
  ['biography includes downtime in quiet stretches', 'src/outages.mjs', 'ms -= Math.max(0, Math.min(end, o.end) - Math.max(start, o.start));', 'ms -= 0;'],
  ['personality forgets all but the last visit', 'src/personality.mjs', 'for (const visit of log.visits)', 'for (const visit of log.visits.slice(-1))'],
  ['personality counts requests rather than repetitions', 'src/personality.mjs', 'next[verb] += n;', 'next[verb] += 1;'],
  ['personality ignores daily care demand', 'src/personality.mjs', 'totals[key] / daily[key]', 'totals[key]'],
  ['balanced personality loses half its weight', 'src/personality.mjs', 'blend.balanced = 3 * shares[low];', 'blend.balanced = 1.5 * shares[low];'],
  ['pair personalities lose half their weight', 'src/personality.mjs', '2 * (shares[middle] - shares[low])', '(shares[middle] - shares[low])'],
  ['personality leaves out the current care', 'src/rock.mjs', 'reaction(afterLog, s, after)', 'reaction(log, s, after)'],
  // The character (CHARACTER.md): its marks, its days, its lines, and that it stays out of the game.
  ['a close call needs no time at the extreme', 'src/engine.mjs', 's.t - since >= GRACE_MS / 2', 's.t - since >= 0'],
  ['close calls are never counted', 'src/engine.mjs', '{ s.closeCalls++; s.brink = false; }', '{ s.brink = false; }'],
  ['a close call counts before the stretch ends', 'src/engine.mjs', 'if (s.brink && s.starvingSince === null && s.sorrowSince === null)', 'if (s.brink)'],
  ['the brink is never left', 'src/engine.mjs', '{ s.closeCalls++; s.brink = false; }', '{ s.closeCalls++; }'],
  ['feeding is not counted', 'src/engine.mjs', '  s.fed += hunger - s.hunger;\n', ''],
  ['petting is not counted', 'src/engine.mjs', '  s.petted += s.happy - happy;\n', ''],
  ['moss starts at 6h', 'src/marks.mjs', 'ms >= 12 * HOUR ? 1', 'ms >= 6 * HOUR ? 1'],
  ['care does not brush the moss off', 'src/marks.mjs', 'const last = s.lastCare ?? s.born;', 'const last = s.born;'],
  ['moss grows through host downtime', 'src/marks.mjs', 'const ms = activeElapsed({ outages }, from, to);', 'const ms = to - from;'],
  ['a grave greens over no further', 'src/marks.mjs', 'd >= 90 * DAY ? 6 : d >= 30 * DAY ? 5 : d >= 7 * DAY ? 4 : 0', '0'],
  ['a grave forgets its last moss', 'src/marks.mjs', 'Math.max(alone(last, s.dead.t), ', 'Math.max(0, '],
  ['more veins than a drawing has room for', 'src/marks.mjs', 'Math.min(3, s.closeCalls)', 'Math.min(9, s.closeCalls)'],
  ['polished sooner', 'src/marks.mjs', 'export const POLISH_AT = [500, 3000];', 'export const POLISH_AT = [300, 3000];'],
  ['a meal is a point of hunger', 'src/marks.mjs', 'const meals = s.fed / R.feed;', 'const meals = s.fed;'],
  ['the dead have no face', 'src/screen.mjs', "if (s.dead) return 'x  x';", "if (s.dead) return '    ';"],
  ['its back is its front', 'src/screen.mjs', "return pose === 'away' ? lines.back : lines.front;", 'return lines.front;'],
  ['moss grows over the rock', 'src/drawings.mjs', 'if (r > 0) top.push([r - 1, c]);', 'if (r > 0) top.push([r, c]);'],
  ['the furrow runs under its base', 'src/screen.mjs', '[left + from, left + dx - 1]', '[left + from, left + dx]'],
  ['no such drawing', 'src/drawings.mjs', "export const DRAWING = 'pip';", "export const DRAWING = 'rock';"],
  ['it faces the wall the day after its day', 'src/character.mjs', '=== nature(s.born).wallDay', '=== (nature(s.born).wallDay + 1) % 7'],
  ['it does odd things at an extreme', 'src/character.mjs', 'if (s.dead || inDanger(s)) return null;', 'if (s.dead) return null;'],
  ['starving counts as no extreme', 'src/character.mjs', 'export const inDanger = s => s.starvingSince !== null || s.sorrowSince !== null;', 'export const inDanger = s => s.sorrowSince !== null;'],
  ['care leaves it facing the wall', 'src/rock.mjs', 'render(after, { now: t, host, ...seen(afterLog, after, t) }) + reaction', "render(after, { now: t, host, ...seen(afterLog, after, t), pose: occasion(after, t)?.what === 'wall' ? 'away' : 'front' }) + reaction"],
  ['it moves in summer too', 'src/character.mjs', '(month === 11 || month <= 1) && ', ''],
  ['it slides before the ice breaks up', 'src/character.mjs', 'd * DAY + SAILS_AT <= t; d++', 'd * DAY <= t; d++'],
  ['the ice can leave it where it was', 'src/wander.mjs', '(spot + 1 + (hash(log.born, 5, e.key) % (spots - 1))) % spots', 'hash(log.born, 5, e.key) % spots'],
  ['it wanders off the screen', 'src/wander.mjs', 'spots = max - min + 1;', 'spots = max - min + 2;'],
  ['a grave keeps moving', 'src/wander.mjs', '    if (s.dead) break;\n', ''],
  ['no furrow', 'src/screen.mjs', 'if (!s.dead && place.furrow && from !== null) {', 'if (false) {'],
  ['a grave keeps its last furrow', 'src/screen.mjs', 'if (!s.dead && place.furrow && from !== null) {', 'if (place.furrow && from !== null) {'],
  ['birthdays drift with leap years', 'src/character.mjs', 'const at = k => Date.UTC(b.getUTCFullYear() + k, b.getUTCMonth(), b.getUTCDate(), b.getUTCHours(), b.getUTCMinutes(), b.getUTCSeconds(), b.getUTCMilliseconds());', 'const at = k => born + k * 365 * DAY;'],
  ['a birthday lasts two days', 'src/character.mjs', 't < at(years) + DAY', 't < at(years) + 2 * DAY'],
  ['a visitor every day', 'src/character.mjs', 'hash(s.born, 6, day) % 8 === 0', 'hash(s.born, 6, day) % 1 === 0'],
  ['two lines on a special day', 'src/rock.mjs', '+ remark(o) +', '+ remark(o) + remark(o) +'],
  ['whimsy at the brink', 'src/story.mjs', "if (after.dead || inDanger(after)) return '';", "if (after.dead) return '';"],
  ['a close call goes unremarked', 'src/story.mjs', 'if (after.closeCalls > before.closeCalls)', 'if (false)'],
  ['it ignores recovery from sorrow', 'src/story.mjs', 'else if (before.sorrowSince !== null) line = pick(RECOVERED);', ''],
  ['it ignores weighted preferences', 'src/story.mjs', '.sort((a, b) => profile.shares[b] - profile.shares[a])', ''],
  ['every visit gets the same line', 'src/story.mjs', 'lines[hash(birth, 8, after.visits) % lines.length]', 'lines[0]'],
  ['a care-derived line is lost', 'src/story.mjs', "'it leans into the attention.'", "'it leans in.'"],
  ['the biography forgets its close calls', 'src/story.mjs', '`close calls: ${s.closeCalls} (up to three veins shown)`', '`close calls: 0 (up to three veins shown)`'],
  ['no sailing in February', 'src/character.mjs', '(month === 11 || month <= 1) && ', '(month === 11 || month === 0) && '],
  ['the ice moves it more rarely', 'src/character.mjs', 'const SAILS_PER_MILLE = 50;', 'const SAILS_PER_MILLE = 30;'],
  ['visitors come one day in four', 'src/character.mjs', 'hash(s.born, 6, day) % 8 === 0', 'hash(s.born, 6, day) % 4 === 0'],
  ['the wall before a slide', 'src/character.mjs', "  if (slidToday(s.born, now, outages)) return { what: 'sailed' };\n", ''],
  // Its name (CHARACTER.md, "Its name").
  ['a name can be given twice', 'src/rock.mjs', 'if (log.name) return { status: 409', 'if (false) return { status: 409'],
  ['a grave can be named', 'src/rock.mjs', 'if (s.dead) return { ...firstSight(log, s), status: 410', 'if (false) return { ...firstSight(log, s), status: 410'],
  ["a taken name is given again", "src/rock.mjs", "if (isTaken(parsed.name, namesOf(taken))) return { status: 409, text: `error: a rock before it had that name, and a name is never given twice. nothing was done.\\n${screen()}` };", ""],
  ['taken names are matched by case', 'src/name.mjs', 'taken.some(t => t.toLowerCase() === name.toLowerCase())', 'taken.includes(name)'],
  ['a name may be any text', 'src/name.mjs', 'export const NAME = /^[A-Za-z]{2,12}$/;', 'export const NAME = /^[^\\n]{1,40}$/;'],
  ['a name is kept as it was sent', 'src/name.mjs', 'return { name: text[0].toUpperCase() + text.slice(1).toLowerCase() };', 'return { name: text };'],
  ['the log takes a second name', 'src/log.mjs', 'if (log.name) throw new Error(`${where} names it a second time`);', ''],
  ['the log takes a name out of time order', 'src/log.mjs', ' || row.t < last) throw new Error(`${where} is not a name`);', ') throw new Error(`${where} is not a name`);'],
  ['a clock behind the name is trusted', 'src/rock.mjs', ', log.name?.t ?? -Infinity);\n}', ');\n}'],
  ['outage credit before the name', 'src/rock.mjs', ', log.outages?.at(-1)?.end ?? -Infinity, log.name?.t ?? -Infinity);\n  if (outage.start < last)', ', log.outages?.at(-1)?.end ?? -Infinity);\n  if (outage.start < last)'],
  ['a name is never written', 'server.mjs', "(r.named ? nameLine(r.named) : '')", "''"],
  ['the graveyard is not read', 'server.mjs', "if (!line.includes('\"named\"')) continue;", 'continue;'],
  ['the screen hides the name', 'src/screen.mjs', 'lines.push(`${name ? `${name}  ` : \'\'}age ${span(now - s.born)}', 'lines.push(`age ${span(now - s.born)}'],
  ['the naming line shows at an extreme', 'src/screen.mjs', 'if (!name && s.sorrowSince === null && s.starvingSince === null) lines.push', 'if (!name) lines.push'],
  // Review round 2.
  ['the naming reply speaks at an extreme', 'src/rock.mjs', "const said = inDanger(s) ? '' : `quirk: ${NAMED}\\n`;", 'const said = `quirk: ${NAMED}\\n`;'],
  ['a reserved word can be a name', 'src/name.mjs', 'if (RESERVED.has(text.toLowerCase())) return', 'if (false) return'],
  ['a folder in the graveyard is read as a log', 'server.mjs', "entries.filter(e => e.isFile() && e.name.endsWith('.jsonl'))", 'entries'],
  ['the graveyard is read only to line 2', 'server.mjs', "fs.readFileSync(path.join(grave, f.name), 'utf8').split('\\n')", "fs.readFileSync(path.join(grave, f.name), 'utf8').split('\\n').slice(0, 2)"],
  ['a name is logged at the raw clock', 'src/rock.mjs', 'const named = { name: parsed.name, t };', 'const named = { name: parsed.name, t: now };'],
  ['the naming reply counts downtime as time alone', 'src/rock.mjs', 'render(s, { now: t, host, ...seen(log, s, t), name: named.name })', 'render(s, { now: t, host, name: named.name })'],
  ['meals shown as points of hunger', 'src/story.mjs', '`meals: ${Math.floor(m.meals)}', '`meals: ${Math.floor(s.fed)}'],
  ['the name dated by the birth', 'src/story.mjs', '(since ${date(log.name.t)})', '(since ${date(log.born)})'],
  ['a different visitor comes', 'src/character.mjs', "return { what: 'visitor', which: hash(s.born, 7, day) };", "return { what: 'visitor', which: hash(s.born, 9, day) };"],
  // Review round 3: paths that were right but unpinned.
  ['the naming reply speaks while only starving', 'src/rock.mjs', "const said = inDanger(s) ? '' :", "const said = s.sorrowSince !== null ? '' :"],
  ['the naming reply speaks while only sad', 'src/rock.mjs', "const said = inDanger(s) ? '' :", "const said = s.starvingSince !== null ? '' :"],
  ['a short extreme ending forgets the long one', 'src/engine.mjs', 'if (long(s.starvingSince) || long(s.sorrowSince)) s.brink = true;', 's.brink = long(s.starvingSince) || long(s.sorrowSince);'],
  ['a grave grows moss as if still alone', 'src/marks.mjs', 'Math.max(alone(last, s.dead.t), ', 'Math.max(alone(last, now), '],
  ['a named grave is refused as named', 'src/rock.mjs', '  if (s.dead) return { ...firstSight(log, s), status: 410, text: screen() };\n', "  if (log.name) return { status: 409, text: 'named' };\n  if (s.dead) return { ...firstSight(log, s), status: 410, text: screen() };\n"],
  ['the history counts slides after death', 'src/story.mjs', '.filter(t => !s.dead || t < s.dead.t)', ''],
  ['the history counts slides in downtime', 'src/story.mjs', 'iceTimes(log.born, now, log.outages ?? [])', 'iceTimes(log.born, now, [])'],
  ['the history counts a slide due as it died', 'src/story.mjs', '.filter(t => !s.dead || t < s.dead.t)', '.filter(t => !s.dead || t <= s.dead.t)'],
  ['a screen word can be a name', 'src/name.mjs', "'just', 'last', 'care', 'never',", "'just', 'last', 'care',"],
  ['a persisted name after computed death is accepted', 'src/rock.mjs', "  if (s.dead && log.name?.t >= s.dead.t) throw new Error('the log contains a name at or after death');\n", ''],
  ['satisfied milestones are silent', 'src/story.mjs', 'else if (after.visits > before.visits && VISITS[after.visits])', 'else if ((did.pet || did.clean || did.feed) && after.visits > before.visits && VISITS[after.visits])'],
  ['later rescues announce undrawn veins', 'src/story.mjs', "after.closeCalls > 3 ? 'it has weathered another close call.' : ", ''],
  ['cleaning never reveals the stone', 'src/story.mjs', 'did.clean && hash(birth, 9, after.visits) % 4 === 0', 'false'],
  // The ground: its personality, drawn (ground.mjs).
  ['a balanced rock shows every trace', 'src/ground.mjs', 'least = Math.min(...shares);', 'least = 0;'],
  ['the ground is full grown at birth', 'src/ground.mjs', 'const grownBy = lived => Math.min(1, lived / (FORMING_DAYS * DAY));', 'const grownBy = lived => 1;'],
  ['the ground keeps growing past two weeks', 'src/ground.mjs', 'const grownBy = lived => Math.min(1, lived / (FORMING_DAYS * DAY));', 'const grownBy = lived => lived / (FORMING_DAYS * DAY);'],
  ['the ground takes three weeks to form', 'src/ground.mjs', 'export const FORMING_DAYS = 14;', 'export const FORMING_DAYS = 21;'],
  ['the first level comes early', 'src/ground.mjs', '[0.3, 0.45, 0.6]', '[0.2, 0.45, 0.6]'],
  ['the second level comes later', 'src/ground.mjs', '[0.3, 0.45, 0.6]', '[0.3, 0.5, 0.6]'],
  ['worn ground fades at once', 'src/ground.mjs', 'export const FADE = 0.02;', 'export const FADE = 0;'],
  ['worn ground fades sooner', 'src/ground.mjs', 'export const FADE = 0.02;', 'export const FADE = 0.01;'],
  ['worn ground fades later', 'src/ground.mjs', 'export const FADE = 0.02;', 'export const FADE = 0.03;'],
  ['worn ground never fades', 'src/ground.mjs', '      while (ground[k] > 0 && trace < LEVELS_AT[ground[k] - 1] - FADE) ground[k]--;\n', ''],
  ['a fall drops every level', 'src/ground.mjs', '      while (ground[k] > 0 && trace < LEVELS_AT[ground[k] - 1] - FADE) ground[k]--;', '      if (ground[k] > 0 && trace < LEVELS_AT[ground[k] - 1] - FADE) ground[k] = 0;'],
  ['a fall drops one level at a time', 'src/ground.mjs', '      while (ground[k] > 0 && trace < LEVELS_AT[ground[k] - 1] - FADE) ground[k]--;', '      if (ground[k] > 0 && trace < LEVELS_AT[ground[k] - 1] - FADE) ground[k]--;'],
  ['a level is reached a hair late', 'src/ground.mjs', 'trace >= LEVELS_AT[ground[k]]', 'trace > LEVELS_AT[ground[k]]'],
  ['no settling before a visit', 'src/ground.mjs', '    settle(visit.t);\n    care = addCare(care, visit.acts);', '    care = addCare(care, visit.acts);'],
  ['no settling after a visit', 'src/ground.mjs', '    traces = tracesOf(care);\n    settle(visit.t);\n', '    traces = tracesOf(care);\n'],
  ['worn ground fades more slowly the higher it is', 'src/ground.mjs', 'trace < LEVELS_AT[ground[k] - 1] - FADE)', 'trace < LEVELS_AT[ground[k] - 1] - FADE * LEVELS_AT[ground[k] - 1] / 0.3)'],
  ['the deepest ground fades twice as slowly', 'src/ground.mjs', 'trace < LEVELS_AT[ground[k] - 1] - FADE)', 'trace < LEVELS_AT[ground[k] - 1] - FADE * (ground[k] === 3 ? 2 : 1))'],
  ["the traces round differently from personality()'s shares", 'src/ground.mjs', 'equivalents.map(e => e / scale / sum)', 'equivalents.map(e => e / (scale * sum))'],
  ['the traces take any totals', 'src/ground.mjs', '  for (const key of CARE_AXES) if (!Number.isFinite(care[key]) || care[key] < 0) throw new Error(`invalid ${key} care total`);\n', ''],
  ['every settle grows to the end', 'src/ground.mjs', 'const grown = grownBy(activeElapsed(log, log.born, t));', 'const grown = grownBy(activeElapsed(log, log.born, end));'],
  ['the traces forget the daily need', 'src/ground.mjs', 'care[key] / DAILY_CARE[key]', 'care[key]'],
  ['the ground grows through downtime', 'src/ground.mjs', 'const grown = grownBy(activeElapsed(log, log.born, t));', 'const grown = grownBy(t - log.born);'],
  ["a grave's ground keeps growing", 'src/rock.mjs', 'ground: groundAt(log, end),', 'ground: groundAt(log, t),'],
  ['the ground is drawn where the rock began', 'src/screen.mjs', 'drawGround(g, ground, rows, dx);', 'drawGround(g, ground, rows, 0);'],
  ['a look shows no ground', 'src/rock.mjs', ', ground: groundAt(log, end),', ','],
  ["a visit's reply shows the ground from before it", 'src/rock.mjs', 'render(after, { now: t, host, ...seen(afterLog, after, t) })', 'render(after, { now: t, host, ...seen(log, after, t) })'],
  ['a refused act shows no ground', 'src/rock.mjs', 'nothing was done.\\n${render(s, { now: t, host, ...seen(log, s, t) })}', 'nothing was done.\\n${render(s, { now: t, host, ...seen(log, s, t), ground: undefined })}'],
  ['a grave answers care with no ground', 'src/rock.mjs', 'if (s.dead) return { status: 410, text: render(s, { now: t, host, ...seen(log, s, t) })', 'if (s.dead) return { status: 410, text: render(s, { now: t, host, ...seen(log, s, t), ground: undefined })'],
  ['a refused name shows no ground', 'src/rock.mjs', 'const screen = () => render(s, { now: t, host, ...seen(log, s, t) })', 'const screen = () => render(s, { now: t, host, ...seen(log, s, t), ground: undefined })'],
  ['a name given shows no ground', 'src/rock.mjs', 'render(s, { now: t, host, ...seen(log, s, t), name: named.name })', 'render(s, { now: t, host, ...seen(log, s, t), name: named.name, ground: undefined })'],
  ['sand on one side only', 'src/ground.mjs', 'for (const c of [left - 1, right + 1])', 'for (const c of [left - 1])'],
  ['light sand fills its row', 'src/ground.mjs', '  if (ground.feed >= 2) {', '  if (ground.feed >= 1) {'],
  ['deep sand leaves bare ground beside it', 'src/ground.mjs', '  if (ground.feed >= 2) {', '  if (ground.feed === 2) {'],
  ['sand never reaches the corners', 'src/ground.mjs', "    for (const c of [left, right]) if (outline(c)) g[BASE][c] = '.';\n", ''],
  ['deep sand buries its marks and moss', 'src/ground.mjs', ' && g[BASE][c] === base[c - dx];', ';'],
  ['light raking spans the whole row', 'src/ground.mjs', 'ground.clean >= 2 ? [0, W - 1] : [left, right]', '[0, W - 1]'],
  ['one raked line at every level', 'src/ground.mjs', 'for (let line = 1; line <= ground.clean; line++)', 'for (let line = 1; line <= Math.min(1, ground.clean); line++)'],
  ['raking stops at two lines', 'src/ground.mjs', 'for (let line = 1; line <= ground.clean; line++)', 'for (let line = 1; line <= Math.min(2, ground.clean); line++)'],
  ['a line is raked where no cleaning leans', 'src/ground.mjs', 'for (let line = 1; line <= ground.clean; line++)', 'for (let line = 1; line <= ground.clean + 1; line++)'],
  ['the raked lines skip rows', 'src/ground.mjs', 'if (bare(BASE + line, c)) g[BASE + line][c] = ', 'if (bare(BASE + 2 * line - 1, c)) g[BASE + 2 * line - 1][c] = '],
  ['footprints walk a straight line', 'src/ground.mjs', '[[6, 3], [7, 4], [8, 3], [9, 4], [10, 3]]', '[[6, 3], [7, 3], [8, 3], [9, 3], [10, 3]]'],
  ['footprints cross the second mess', 'src/ground.mjs', '[[6, 3], [7, 4], [8, 3], [9, 4], [10, 3]]', '[[6, 3], [7, 2], [8, 3], [9, 2], [10, 3]]'],
  ['footprints stay put when it moves', 'src/ground.mjs', 'const c = col + dx;', 'const c = col;'],
  ['more petting wears no more footprints', 'src/ground.mjs', 'export const STEPS = [0, 2, 3, 5];', 'export const STEPS = [0, 2, 3, 3];'],
  ['footprints never step on a stone', 'src/ground.mjs', "    else if (g[r][c] === '-') g[r][c] = 'o';\n", ''],
  ['stones only on the first raked line', 'src/ground.mjs', "    else if (g[r][c] === '-') g[r][c] = 'o';", "    else if (g[r][c] === '-' && r === BASE + 1) g[r][c] = 'o';"],
  ['the furrow is drawn in sand', 'src/screen.mjs', "c <= Math.min(W - 1, z); c++) g[5][c] = '~';", "c <= Math.min(W - 1, z); c++) g[5][c] = '.';"],
  ['the furrow goes under the sand', 'src/screen.mjs', "c <= Math.min(W - 1, z); c++) g[5][c] = '~';", "c <= Math.min(W - 1, z); c++) if (g[5][c] === ' ') g[5][c] = '~';"],
  // Its meals and its hunger (meal.mjs, screen.mjs).
  ['a meal lasts two hours', 'src/meal.mjs', 'export const MEAL_MS = HOUR;', 'export const MEAL_MS = 2 * HOUR;'],
  ['a meal lasts half an hour', 'src/meal.mjs', 'export const MEAL_MS = HOUR;', 'export const MEAL_MS = HOUR / 2;'],
  ['the food is never eaten down', 'src/meal.mjs', "export const FOOD = ['#', '+'];", "export const FOOD = ['#', '#'];"],
  ['the food goes in thirds', 'src/meal.mjs', 'Math.floor((ms * FOOD.length) / MEAL_MS)', 'Math.floor((ms * 3) / MEAL_MS)'],
  ['a faint tick beside a polish slot', 'src/drawings.mjs', `faint: { front: ['', '    ...', '  .:   :..',`, `faint: { front: ['', '    ...', "  .'   '..",`],
  ['the mouth opens in odd minutes', 'src/meal.mjs', 'Math.floor(ms / MINUTE) % 2 === 0', 'Math.floor(ms / MINUTE) % 2 === 1'],
  ["the mouth keeps the clock's minutes, not the meal's", 'src/meal.mjs', 'Math.floor(ms / MINUTE) % 2 === 0', 'Math.floor(now / MINUTE) % 2 === 0'],
  ['a meal runs through host downtime', 'src/meal.mjs', 'const ms = activeElapsed(log, v.t, now);', 'const ms = now - v.t;'],
  ['any care starts a meal', 'src/meal.mjs', "if (v.acts.some(([verb]) => verb === 'feed'))", 'if (true)'],
  ['care after a feed ends the meal', 'src/meal.mjs', "if (v.acts.some(([verb]) => verb === 'feed')) return", "if (!v.acts.some(([verb]) => verb === 'feed')) return null;\n    return"],
  ['a meal shows before its feed', 'src/meal.mjs', '    if (v.t > now) continue;\n', ''],
  ['the food always goes on its left', 'src/meal.mjs', 'onRight = right + 1 < W', 'onRight = false'],
  ['the food goes past the edge', 'src/meal.mjs', 'onRight = right + 1 < W', 'onRight = true'],
  ['the food sits a cell off', 'src/meal.mjs', 'g[r][onRight ? end + 1 : end - 1] = meal.food;', 'g[r][onRight ? end + 2 : end - 2] = meal.food;'],
  ['its mouth shows from behind', 'src/meal.mjs', "if (meal.open && pose !== 'away')", 'if (meal.open)'],
  ['its mouth never shuts', 'src/meal.mjs', "if (meal.open && pose !== 'away')", "if (pose !== 'away')"],
  ['its mouth opens away from the food', 'src/meal.mjs', "onRight ? '<' : '>'", "onRight ? '>' : '<'"],
  ['a grave eats', 'src/screen.mjs', 'if (meal && !s.dead)', 'if (meal)'],
  ['the food is drawn a row low', 'src/screen.mjs', ".findIndex(row => row.includes('E')), dx, pose);", ".findIndex(row => row.includes('E')) + 1, dx, pose);"],
  ['a look shows no meal', 'src/rock.mjs', ', meal: mealAt(log, t),', ','],
  ['never faint', 'src/screen.mjs', 'const lines = faint(s) ? drawing.faint : drawing;', 'const lines = drawing;'],
  ['faint from hunger 6', 'src/screen.mjs', 'export const FAINT_AT = 7;', 'export const FAINT_AT = 6;'],
  ['faint from hunger 8', 'src/screen.mjs', 'export const FAINT_AT = 7;', 'export const FAINT_AT = 8;'],
  ['faint by its true hunger, not the shown one', 'src/screen.mjs', 'shownHunger(s) >= FAINT_AT', 's.hunger >= FAINT_AT'],
  ['a grave is drawn faint', 'src/screen.mjs', 'export const faint = s => !s.dead && ', 'export const faint = s => '],
  ['its back is never faint', 'src/screen.mjs', "return pose === 'away' ? lines.back : lines.front;", "return pose === 'away' ? drawing.back : lines.front;"],
  // Where it is (wander.mjs).
  ['it wanders every two hours', 'src/wander.mjs', 'export const WANDER_H = 4;', 'export const WANDER_H = 2;'],
  ['it wanders every eight hours', 'src/wander.mjs', 'export const WANDER_H = 4;', 'export const WANDER_H = 8;'],
  ['it wanders on the hour', 'src/wander.mjs', '(hash(log.born, 12, k) % (WANDER_H * 60)) * MINUTE', '0'],
  ['it never rests', 'src/wander.mjs', 'export const REST_MS = HOUR;', 'export const REST_MS = 0;'],
  ['it rests two hours', 'src/wander.mjs', 'export const REST_MS = HOUR;', 'export const REST_MS = 2 * HOUR;'],
  ['its furrow shows two hours', 'src/wander.mjs', 'export const FURROW_MS = HOUR;', 'export const FURROW_MS = 2 * HOUR;'],
  ['it wanders at an extreme', 'src/wander.mjs', "    if (e.why !== 'ice' && inDanger(s)) continue;\n", ''],
  ['only starving holds it still', 'src/wander.mjs', "    if (e.why !== 'ice' && inDanger(s)) continue;\n", "    if (e.why !== 'ice' && s.starvingSince !== null) continue;\n"],
  ['it wanders while it rests', 'src/wander.mjs', ' || (at !== null && activeElapsed(log, at, e.t) < REST_MS)) continue;', ') continue;'],
  ['its rest runs through downtime', 'src/wander.mjs', 'activeElapsed(log, at, e.t) < REST_MS', 'e.t - at < REST_MS'],
  ['its rest ends a moment late', 'src/wander.mjs', 'activeElapsed(log, at, e.t) < REST_MS', 'activeElapsed(log, at, e.t) <= REST_MS'],
  ['it wanders before its food', 'src/wander.mjs', 'const ORDER = { ice: 0, food: 1, wander: 2 };', 'const ORDER = { ice: 0, food: 2, wander: 1 };'],
  ['its food before the ice', 'src/wander.mjs', 'const ORDER = { ice: 0, food: 1, wander: 2 };', 'const ORDER = { ice: 1, food: 0, wander: 2 };'],
  ['downtime ending at its minute stops it', 'src/wander.mjs', 'some(o => t >= o.start && t < o.end)) continue;', 'some(o => t >= o.start && t <= o.end)) continue;'],
  ['downtime starting at its minute lets it go', 'src/wander.mjs', 'some(o => t >= o.start && t < o.end)) continue;', 'some(o => t > o.start && t < o.end)) continue;'],
  ['the ice slides it in downtime', 'src/wander.mjs', 'iceTimes(log.born, end, log.outages ?? [])', 'iceTimes(log.born, end, [])'],
  ['a drawing with no room is drawn anyway', 'src/wander.mjs', "  if (!(spots >= 2)) throw new Error('a drawing must leave it room to move');\n", ''],
  ['it wanders through downtime', 'src/wander.mjs', ' || (log.outages ?? []).some(o => t >= o.start && t < o.end)) continue;', ') continue;'],
  ['it never goes to its food', 'src/wander.mjs', "...log.visits.filter(v => v.t <= end && v.acts.some(([verb]) => verb === 'feed'))", '...log.visits.filter(v => false)'],
  ['any visit sends it off', 'src/wander.mjs', "v.t <= end && v.acts.some(([verb]) => verb === 'feed')", 'v.t <= end'],
  ['it wanders on after the ice', 'src/wander.mjs', "    if (e.why === 'ice') iced = (Math.floor(e.t / DAY) + 1) * DAY;\n", ''],
  ['the ice rests it two days', 'src/wander.mjs', 'iced = (Math.floor(e.t / DAY) + 1) * DAY;', 'iced = (Math.floor(e.t / DAY) + 2) * DAY;'],
  ['it leaves its food', 'src/wander.mjs', "      if (e.why === 'wander' && fed !== null && activeElapsed(log, fed, e.t) < MEAL_MS) continue; // it is eating\n", ''],
  ['it forgets its food', 'src/wander.mjs', "    if (e.why === 'food') fed = e.t;\n", ''],
  ['its meal runs through downtime, for wandering', 'src/wander.mjs', 'activeElapsed(log, fed, e.t) < MEAL_MS', 'e.t - fed < MEAL_MS'],
  ['its meal ends a moment late, for wandering', 'src/wander.mjs', 'activeElapsed(log, fed, e.t) < MEAL_MS', 'activeElapsed(log, fed, e.t) <= MEAL_MS'],
  ['midnight after the ice still rests it', 'src/wander.mjs', 'e.t < iced', 'e.t <= iced'],
  ['the feed that brings it back is judged before it', 'src/wander.mjs', '    const s = stateAt(e.t);', "    const s = stateAt(e.why === 'food' ? e.t - 1 : e.t);"],
  ['no chance in the four hours it was born in', 'src/wander.mjs', 'for (let k = Math.floor((log.checkpoint?.engine.t ?? log.born) / BLOCK); k * BLOCK <= end; k++)', 'for (let k = Math.floor(log.born / BLOCK) + 1; k * BLOCK <= end; k++)'],
  ["a feed's spot follows its millisecond", 'src/wander.mjs', 'key: Math.floor(v.t / (WANDER_H * HOUR))', 'key: v.t'],
  ["a feed's spot follows its minute", 'src/wander.mjs', 'key: Math.floor(v.t / (WANDER_H * HOUR))', 'key: Math.floor(v.t / MINUTE)'],
  ["a feed's spot follows its hour", 'src/wander.mjs', 'key: Math.floor(v.t / (WANDER_H * HOUR))', 'key: Math.floor(v.t / HOUR)'],
  ['its food has a spot of its own', 'src/wander.mjs', ': hash(log.born, 10, e.key) % spots;', ": hash(log.born, e.why === 'food' ? 11 : 10, e.key) % spots;"],
  ['a stay starts a rest', 'src/wander.mjs', '    if (to === spot) continue;\n', '    if (to === spot) { at = e.t; continue; }\n'],
  ['its first chance waits an hour after its birth', 'src/wander.mjs', 'if (t <= log.born ||', 'if (t <= log.born + HOUR ||'],
  ['it slides on the day it was born', 'src/character.mjs', 'for (let d = dayOf(born) + 1;', 'for (let d = dayOf(born);'],
  ["moss on the back is the front's", 'src/screen.mjs', 'mossCells(rows).slice(0, MOSS_CELLS', 'mossCells(drawing.front).slice(0, MOSS_CELLS'],
  ["the ice's furrow goes in an hour", 'src/wander.mjs', "return place.why === 'ice' ? Math.floor(now / DAY) === Math.floor(place.at / DAY) : activeElapsed(log, place.at, now) < FURROW_MS;", 'return activeElapsed(log, place.at, now) < FURROW_MS;'],
  ['its furrow runs through downtime', 'src/wander.mjs', ': activeElapsed(log, place.at, now) < FURROW_MS;', ': now - place.at < FURROW_MS;'],
  ['a walk to food leaves a wall-clock furrow', 'src/wander.mjs', ': activeElapsed(log, place.at, now) < FURROW_MS;', ": (place.why === 'food' ? now - place.at : activeElapsed(log, place.at, now)) < FURROW_MS;"],
  ["the screen's furrow forgets downtime", 'src/rock.mjs', 'furrow: furrowShows(log, place, t)', 'furrow: furrowShows({}, place, t)'],
  ['it slides while the host is down', 'src/character.mjs', ' && !outages.some(o => at >= o.start && at < o.end)', ''],
  ['downtime ending at 10:00 stops the slide', 'src/character.mjs', 'at >= o.start && at < o.end', 'at >= o.start && at <= o.end'],
  ['downtime starting at 10:00 lets it slide', 'src/character.mjs', 'at >= o.start && at < o.end', 'at > o.start && at < o.end'],
  ['a look forgets downtime for its remark', 'src/rock.mjs', 'const o = occasion(s, t, log.outages ?? []);', 'const o = occasion(s, t, []);'],
  ['moss grows off the grid', 'src/screen.mjs', "    if (col + dx >= 0 && col + dx < W) b[row][col] = i % 3 === 2 ? '\"' : ',';", "    b[row][col] = i % 3 === 2 ? '\"' : ',';"],
  ['moss skips past the edge', 'src/screen.mjs', 'mossCells(rows).slice(0, MOSS_CELLS[mossAt(s, now, outages)]).entries()', 'mossCells(rows).filter(([, col]) => col + dx >= 0 && col + dx < W).slice(0, MOSS_CELLS[mossAt(s, now, outages)]).entries()'],
  ['a grave grows no second layer', 'src/drawings.mjs', '  const layer = top.filter(([r]) => r > 0).map(([r, c]) => [r - 1, c]);', '  const layer = [];'],
  ['the screen grows moss as if it were at home', 'src/screen.mjs', 'sprite(s, now, pose, drawing, outages, dx).forEach', 'sprite(s, now, pose, drawing, outages).forEach'],
  ['it is drawn where it began', 'src/screen.mjs', '  const { dx, from } = place;', '  const { from } = place, dx = 0;'],
  ['a look draws it where it began', 'src/rock.mjs', 'place: { dx: place.dx, from: place.from, furrow: furrowShows(log, place, t) },', 'place: { dx: 0, from: null, furrow: false },'],
  ['sand does not know a faint base', 'src/screen.mjs', 'drawGround(g, ground, rows, dx);', "drawGround(g, ground, pose === 'away' ? drawing.back : drawing.front, dx);"],
  ['a faint base in dots, like sand', 'src/drawings.mjs', `' :  E  E  :', " '________'"], back: ['', '     ...',`, `' :  E  E  :', " '........'"], back: ['', '     ...',`],
  ['a faint back out of step with its front', 'src/drawings.mjs', `back: ['', '    ....', "  .'    '.", ' :        :',`, `back: ['', '    ....', "  .'    '.", ' .        .',`],
  ["a log that turns up is never served", "server.mjs", "    if (!hasBegun()) return false;\n    started = true;", "    return false;\n    started = true;"],
  ["a log that turns up is not latched", "server.mjs", "    started = true;\n    markOnce(file);\n    return true;", "    markOnce(file);\n    return true;"],
  ["the server factory forgets a begun mark", "server.mjs", "const hasBegun = () => present(file) || present(begunOf(file));", "const hasBegun = () => present(file);"],
  ["--new-rock ignores an existing log", "server.mjs", "if (present(file) || present(begunOf(file))) throw new Error('--new-rock", "if (present(begunOf(file))) throw new Error('--new-rock"],
  ["--new-rock ignores a begun mark", "server.mjs", "if (present(file) || present(begunOf(file))) throw new Error('--new-rock", "if (present(file)) throw new Error('--new-rock"],
  ["a start writes no name", "server.mjs", "birthLine(r.born) + nameLine(r.named)", "birthLine(r.born)"],
  ["the title screen cares for no rock", "server.mjs", "() => titled(409, 'error: there is no rock yet: name one to start it. nothing was done.\\n')", "() => withLog((log, t) => act(log, body, { now: t, host }))"],
  ["the title screen gives a taken name", "src/rock.mjs", "  if (isTaken(parsed.name, namesOf(taken))) return { status: 409, text: `error: a rock before it had that name, and a name is never given twice. nothing was done.\\n${again()}` };\n", ""],
  ["a started rock has no name", "src/rock.mjs", "const log = { ...newLog(now), name: named };", "const log = newLog(now);"],
  ["a rock is named after its birth", "src/rock.mjs", "const named = { name: parsed.name, t: now };", "const named = { name: parsed.name, t: now + 1 };"],
  ["the title screen says nothing of feeding", "src/screen.mjs", "    `feed: hunger -${R.feed} (it rises ${R.hungerPerHour * 24} a day)`,\n", ""],
  ["a start is not the start at once", "server.mjs", "    started = true;\n    fs.writeFileSync(begunOf(file), markOf(r.born, r.named), { flag: 'wx' });", "    fs.writeFileSync(begunOf(file), markOf(r.born, r.named), { flag: 'wx' });"],
  ["a start writes over a log", "server.mjs", "birthLine(r.born) + nameLine(r.named), { flag: 'wx' }", "birthLine(r.born) + nameLine(r.named), { flag: 'w' }"],
  ["a start leaves no mark", "server.mjs", "    fs.writeFileSync(begunOf(file), markOf(r.born, r.named), { flag: 'wx' });\n", ""],
  ["a lost log at start is a new game", "server.mjs", "    } else if (present(begunOf(file))) {\n      throw new Error(`a rock began here", "    } else if (false) {\n      throw new Error(`a rock began here"],
  ["a rock from before gets no mark", "server.mjs", "  if (started) markOnce(file);\n", ""],
  ["a failed check reads as no rock", "server.mjs", "const present = file => fs.statSync(file, { throwIfNoEntry: false }) !== undefined;", "const present = file => fs.existsSync(file);"],
  ["a visit is routed on arrival", "server.mjs", "if (route === '/act') return withBody(body => either((log, t) => act(log, body, { now: t, host }), () => titled(409, 'error: there is no rock yet: name one to start it. nothing was done.\\n')));", "if (route === '/act') { const was = isStarted(); return withBody(body => reply(() => (was ? withLog((log, t) => act(log, body, { now: t, host })) : titled(409, 'error: there is no rock yet: name one to start it. nothing was done.\\n')))); }"],
  ["a name is routed on arrival", "server.mjs", "return withBody(body => either((log, t) => name(log, body, { now: t, host, taken: () => takenNames(file) }), () => begin(body)));", "{ const was = isStarted(); return withBody(body => reply(() => (was ? withLog((log, t) => name(log, body, { now: t, host, taken: () => takenNames(file) })) : begin(body)))); }"],
  ["a word of the title screen can be a name", "src/name.mjs", "'dies', ", ""],
  ["a log that turns up is not marked", "server.mjs", "    started = true;\n    markOnce(file);\n    return true;", "    started = true;\n    return true;"],
  ["a start writes over a mark", "server.mjs", "markOf(r.born, r.named), { flag: 'wx' }", "markOf(r.born, r.named), { flag: 'w' }"],
  ["the mark has no name", "server.mjs", "markOf(r.born, r.named), { flag: 'wx' }", "markOf(r.born, null), { flag: 'wx' }"],
  ["naming an old rock leaves its mark without it", "server.mjs", "    if (r.named) fs.writeFileSync(begunOf(file), markOf(log.born, r.named)); // the mark has the name first\n", ""],
  ["an unreadable graveyard has no names", "server.mjs", "try { entries = fs.readdirSync(grave, { withFileTypes: true }); } catch (e) { if (e.code === 'ENOENT') return []; throw e; }", "try { entries = fs.readdirSync(grave, { withFileTypes: true }); } catch (e) { return []; }"],
  ["an unreadable grave has no name", "server.mjs", "    for (const line of fs.readFileSync(path.join(grave, f.name), 'utf8').split('\\n')) {", "    let text = ''; try { text = fs.readFileSync(path.join(grave, f.name), 'utf8'); } catch {}\n    for (const line of text.split('\\n')) {"],
  ["a name asks the graveyard first", "server.mjs", "name(log, body, { now: t, host, taken: () => takenNames(file) })", "name(log, body, { now: t, host, taken: takenNames(file) })"],
];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const work = fs.mkdtempSync(path.join(os.tmpdir(), 'rockpet-mutate-'));
for (const p of ['src', 'test', 'hosting', 'hosting-test', 'drizzle', 'tools/rocksim.mjs', 'tools/sandbox.mjs', 'tools/credit-outage.mjs', 'tools/model-sheet.mjs', 'server.mjs', 'package.json', 'CHARACTER.md', 'DESIGN-NOTES.md']) fs.cpSync(path.join(root, p), path.join(work, p), { recursive: true });
// The suite's own temporary directories go inside the copy too (os.tmpdir() reads TMPDIR, TMP or
// TEMP). A mutant can stop a test before its cleanup, in a hang the timeout kills or a failure
// --test-force-exit walks away from; whatever that leaves is removed with the copy.
const tmp = path.join(work, 'tmp');
fs.mkdirSync(tmp);
const env = { ...process.env, TMPDIR: tmp, TMP: tmp, TEMP: tmp };

// The suite's verdict: the names of the top-level tests that failed (TAP, one process).
function suite() {
  const r = spawnSync(process.execPath, ['--test', '--test-force-exit', '--test-reporter=tap'], { cwd: work, env, encoding: 'utf8', timeout: 120_000 });
  if (r.error?.code === 'ETIMEDOUT') return { failed: ['(timed out)'] };
  const failed = [...r.stdout.matchAll(/^not ok [0-9]+ - (.*)$/gm)].map(m => m[1]);
  if (r.status !== 0 && failed.length === 0) failed.push(`(exit ${r.status}) ${r.stderr.split('\n')[0]}`);
  return { failed };
}

let bad = 0;
const control = suite();
const left = fs.readdirSync(tmp); // a passing suite removes every temporary directory it makes
if (control.failed.length || left.length) {
  if (control.failed.length) console.error(`the unmutated suite fails, so nothing can be learned: ${control.failed.join('; ')}`);
  else console.error(`the unmutated suite passes but leaves temporary directories behind: ${left.join(', ')}`);
  fs.rmSync(work, { recursive: true, force: true });
  process.exit(1);
}
console.log(`control: the unmutated suite passes. ${MUTANTS.length} mutants:\n`);
for (const [name, rel, find, replace] of MUTANTS) {
  const file = path.join(work, rel);
  const original = fs.readFileSync(file, 'utf8').replaceAll('\r\n', '\n');
  const hits = original.split(find).length - 1;
  if (hits !== 1) { console.log(`  BROKEN    ${name}: its text occurs ${hits} times in ${rel}`); bad++; continue; }
  let failed;
  try {
    fs.writeFileSync(file, original.split(find).join(replace));
    ({ failed } = suite());
  } finally {
    fs.writeFileSync(file, original);
  }
  if (failed.length === 0) bad++;
  console.log(`  ${failed.length ? 'caught' : 'SURVIVED'}  ${name}${failed.length ? ` (${failed.length}: ${failed.slice(0, 2).join('; ')}${failed.length > 2 ? '; ...' : ''})` : ''}`);
}
fs.rmSync(work, { recursive: true, force: true });
console.log(`\n${MUTANTS.length - bad} of ${MUTANTS.length} caught`);
process.exit(bad ? 1 : 0);
